<?php
 $labels = array(
    'name'                  => _x( 'Multiple Payment Attempt Failures', 'Post type general name', 'hello-elementor-child' ),
    'singular_name'         => _x( 'Multiple Payment Attempt Failure', 'Post type singular name', 'hello-elementor-child' ),
    'menu_name'             => _x( 'Multiple Payment Failures', 'Admin Menu text', 'hello-elementor-child' ),
    'name_admin_bar'        => _x( 'Payment Failure', 'Add New on Toolbar', 'hello-elementor-child' ),
    'add_new'               => __( 'Add New', 'hello-elementor-child' ),
    'add_new_item'          => __( 'Add New Payment Failure', 'hello-elementor-child' ),
    'new_item'              => __( 'New Payment Failure', 'hello-elementor-child' ),
    'edit_item'             => __( 'Edit Payment Failure', 'hello-elementor-child' ),
    'view_item'             => __( 'View Payment Failure', 'hello-elementor-child' ),
    'all_items'             => __( 'All Payment Failures', 'hello-elementor-child' ),
    'search_items'          => __( 'Search Payment Failures', 'hello-elementor-child' ),
    'parent_item_colon'     => __( 'Parent Payment Failures:', 'hello-elementor-child' ),
    'not_found'             => __( 'No payment failures found.', 'hello-elementor-child' ),
    'not_found_in_trash'    => __( 'No payment failures found in Trash.', 'hello-elementor-child' ),
    'featured_image'        => _x( 'Payment Failure Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'set_featured_image'    => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'use_featured_image'    => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'archives'              => _x( 'Payment Failure archives', 'The post type archive label used in nav menus. Added in 4.4', 'hello-elementor-child' ),
    'insert_into_item'      => _x( 'Insert into payment failure', 'Overrides the “Insert into post” phrase. Added in 4.4', 'hello-elementor-child' ),
    'uploaded_to_this_item' => _x( 'Uploaded to this payment failure', 'Overrides the “Uploaded to this post” phrase. Added in 4.4', 'hello-elementor-child' ),
    'filter_items_list'     => _x( 'Filter payment failures list', 'Screen reader text for the filter links heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
    'items_list_navigation' => _x( 'Payment failures list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
    'items_list'            => _x( 'Payment failures list', 'Screen reader text for the items list heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
);

$args = array(
    'labels'             => $labels,
    'public'             => true,
    'publicly_queryable' => true,
    'show_ui'            => true,
    'show_in_menu'       => true,
    'menu_icon'          => 'dashicons-shield-alt',
    'show_in_rest'       => true,
    'query_var'          => true,
    'rewrite'            => array( 'slug' => 'multiple-attempt' ),
    'capability_type'    => 'post',
    'has_archive'        => true,
    'hierarchical'       => false,
    'menu_position'      => null,
    'supports'           => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' ),
);

register_post_type( 'multiple_attempt', $args );


$support_request_labels = array(
    'name'                  => _x( 'Support Requests', 'Post type general name', 'hello-elementor-child' ),
    'singular_name'         => _x( 'Support Request', 'Post type singular name', 'hello-elementor-child' ),
    'menu_name'             => _x( 'Support Requests', 'Admin Menu text', 'hello-elementor-child' ),
    'name_admin_bar'        => _x( 'Support Request', 'Add New on Toolbar', 'hello-elementor-child' ),
    'add_new'               => __( 'Add New', 'hello-elementor-child' ),
    'add_new_item'          => __( 'Add New Support Request', 'hello-elementor-child' ),
    'new_item'              => __( 'New Support Request', 'hello-elementor-child' ),
    'edit_item'             => __( 'Edit Support Request', 'hello-elementor-child' ),
    'view_item'             => __( 'View Support Request', 'hello-elementor-child' ),
    'all_items'             => __( 'Support Requests', 'hello-elementor-child' ),
    'search_items'          => __( 'Search Support Requests', 'hello-elementor-child' ),
    'parent_item_colon'     => __( '', 'hello-elementor-child' ),
    'not_found'             => __( 'No support requests found.', 'hello-elementor-child' ),
    'not_found_in_trash'    => __( 'No support requests found in Trash.', 'hello-elementor-child' ),
    'featured_image'        => _x( 'Support Request Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'set_featured_image'    => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'use_featured_image'    => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'hello-elementor-child' ),
    'archives'              => _x( 'Support Request archives', 'The post type archive label used in nav menus. Added in 4.4', 'hello-elementor-child' ),
    'insert_into_item'      => _x( 'Insert into support request', 'Overrides the “Insert into post” phrase. Added in 4.4', 'hello-elementor-child' ),
    'uploaded_to_this_item' => _x( 'Uploaded to this support request', 'Overrides the “Uploaded to this post” phrase. Added in 4.4', 'hello-elementor-child' ),
    'filter_items_list'     => _x( 'Filter support requests list', 'Screen reader text for the filter links heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
    'items_list_navigation' => _x( 'Support requests list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
    'items_list'            => _x( 'Support requests list', 'Screen reader text for the items list heading on the post type listing screen. Added in 4.4', 'hello-elementor-child' ),
);

$support_request_args = array(
    'labels'             => $support_request_labels,
    'public'             => true,
    'publicly_queryable' => false,
    'show_ui'            => true,
    'show_in_menu'       => 'woocommerce',
    'menu_icon'          => 'dashicons-universal-access',
    'show_in_rest'       => true,
    'query_var'          => true,
    'rewrite'            => array( 'slug' => 'support-request' ),
    'capability_type'    => 'post',
    'has_archive'        => true,
    'hierarchical'       => true,
    'menu_position'      => null,
    'supports'           => array( 'title', 'editor', 'author', 'excerpt', 'page-attributes' ),
);
register_post_type( 'support_request', $support_request_args );